kind: PersistentVolume
apiVersion: v1
metadata:
  name: kfsummit-workspace
  namespace: kfsummit
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/workspace"
